name: 'docker-github-basic-action'
description: 'print the input json'
inputs:
  input-values:
    description: 'input values we entered'
    required: true
    default: '{}'
outputs:
  op:
    description: 'output values we entered'
runs:
  using: 'docker'
  image: alpine:latest
  args:
    - echo
    - ${{ inputs.input-values }}
